### ISSUE TITLE
update cookbook on supermarket

### ISSUE THREAD

**Issue by meganuke19** [TD-4242/zabbix-agent#14]
Hello.
Do you plan update the cookbook on supermarket?

**Comment by TD-4242** [comment]
The only current commits and changes are in testing infrastructure.  Is there a particular feature you are looking for?

**Comment by meganuke19** [comment]
Need remove recommended dependency to libzabbix.
As set berkshelf policy- recommends/suggests == required.
https://www.bountysource.com/issues/7689578-berkshelf-treats-recommends-as-depends some problem.

**Comment by TD-4242** [comment]
OK, I have some other test fixes I need put in and will remove that dependency.

**Comment by TD-4242** [comment]
Slow release much...I have a new update if you'd like to revew the last 0.14.0 release.  I can publish it to supermarket in a few days.
